name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ${{ matrix.operating_system }}
        strategy:
          matrix:
            nodejs_version: [18, 19, 20]
            operating_system: [ubuntu-latest]
            exclude:
                - nodejs_version: 18
                  operating_system: macos-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Setup NodeJS version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.nodejs_version }}
        
        - name: Cache NPM dependencies
          uses: actions/cache@v5
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install Dependencies
          run: npm install
        
        - name: Unit Testing
          id: NodeJS-unit-testing-step
          run: npm test

        - name: Archive Test results
          if: always()
          uses: actions/upload-artifact@v7
          with:
            name: Mocha-test-result ${{ matrix.nodejs_version }}
            path: test-results ${{ matrix.nodejs_version }}.xml
    
    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        continue-on-error: true
        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Setup NodeJS version - 18
          uses: actions/setup-node@v6
          with:
            node-version: 18

        - name: Cache NPM dependencies
          uses: actions/cache@v5
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install Dependencies
          run: npm install

        - name: Check Code Coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive test results
          uses: actions/upload-artifact@v7
          with:
            name: Code-coverage-result ${{ matrix.nodejs_version }}
            path: coverage
            retention-days: 5
    
    Docker:
      name: Containerization
      needs: [unit-testing, code-coverage]
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dockerhub Login
        uses: docker/login-action@2.2.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
