name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs_version: [20]
        operating_system: [ubuntu-latest]


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup NodeJS version - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.nodejs_version }}
      
      - name: Cache NPM dependencies
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install
      
      - name: Unit Testing
        id: NodeJS-unit-testing-step
        run: npm test

      - name: Archive Test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Mocha-test-result-nodeJS-${{ matrix.nodejs_version }}
          path: test-results-nodeJS-${{ matrix.nodejs_version }}.xml

  code-coverage:
    name: Code Coverage
    container:
      image: node:18
      env:
        MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
        MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      # - name: Setup NodeJS version - 18
      #   uses: actions/setup-node@v6
      #   with:
      #     node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Code-coverage-result
          path: coverage
          retention-days: 5

  Docker:
    name: Containerization
    needs: [unit-testing, code-coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dockerhub Login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Docker build for testing
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system-lab:${{ github.sha }}
          build-args: |
            MONGO_URI='mongodb+srv://supercluster.d83jj.mongodb.net/superData'
            MONGO_USERNAME=${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}

      - name: Docker Image Testing
        run: |
          docker images
          docker run --name solar-system-app -d -p 3000:3000 \
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system-lab:${{ github.sha }}
          
          docker exec solar-system-app printenv | grep -E "MONGO_URI|MONGO_USERNAME|MONGO_PASSWORD"

          IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo "Container IP: $IP"

          echo "Testing image URL using wget"
          wget -q -O - 127.0.0.1:3000/live | grep live

      - name: Docker Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system-lab:${{ github.sha }}
          build-args: |
            MONGO_URI='mongodb+srv://supercluster.d83jj.mongodb.net/superData'
            MONGO_USERNAME=${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}